### ISSUE TITLE
Multiline log messages are printed incorrectly

### ISSUE THREAD

**Issue by FliegendeWurst** [deinstapel/cursive-flexi-logger-view#3]
Log messages containing newlines are printed like this: (using the termion backend)
```
line1
     line2
          line3
```

I fixed the issue myself (WIP: https://github.com/FliegendeWurst/cursive-flexi-logger-view/commit/b2a84f625559c4d019240844d2c58373c3de2ee9) and will open a PR soon.

**Comment by fin-ger** [comment]
I'm happy to review your PR!
